---
server:
    install: '1'
    timezone: America/Mexico_City
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.10.8, memory: '1024', sharedfolder: ./, syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant
    servername: php-queues
rabbitmq:
    install: '1'
    user: osvaldo
    password: osvaldo
    plugins: [rabbitmq_management]
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-fpm]
composer:
    install: '1'

